/**
 * GETTERS
 */
export const NETWORK = 'NETWORK';
export const ADDRESS = 'ADDRESS';
export const USERNAME = 'USERNAME';
export const AVATAR = 'AVATAR';
export const USERNAME_EXISTENCE = 'USERNAME_EXISTENCE';
export const EDIT_PROFILE_RESULT = 'EDIT_PROFILE_RESULT';
export const CREATED_ASSETS_PACKS_IDS = 'CREATED_ASSETS_PACKS_IDS';
export const BOUGHT_ASSETS_PACKS_IDS = 'BOUGHT_ASSETS_PACKS_IDS';
export const BALANCES = 'BALANCES';
export const BANNED_ASSET_PACK_IDS = 'BANNED_ASSET_PACK_IDS';
export const BANNED_CRYPTOGRAPHIC_IDS = 'BANNED_CRYPTOGRAPHIC_IDS';
export const NOTIFICATIONS = 'NOTIFICATIONS';
export const PROVIDER_CONNECTED = 'PROVIDER_CONNECTED';

/**
 * ACTIONS
 */
export const SET_NETWORK = 'SET_NETWORK';
export const SET_ADDRESS = 'SET_ADDRESS';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_NEW_USERNAME = 'SET_NEW_USERNAME';
export const SET_AVATAR = 'SET_AVATAR';
export const SET_USER_CONFIG = 'SET_USER_CONFIG';
export const SET_CREATED_ASSETS_PACKS_IDS = 'SET_CREATED_ASSETS_PACKS_IDS';
export const SET_BOUGHT_ASSETS_PACKS_IDS = 'SET_BOUGHT_ASSETS_PACKS_IDS';
export const UPDATE_USER_CONFIG = 'UPDATE_USER_CONFIG';
export const CHECK_USERNAME_EXISTENCE = 'CHECK_USERNAME_EXISTENCE';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const FETCH_BALANCES = 'FETCH_BALANCES';
export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
export const SET_APPROVAL = 'SET_APPROVAL';
export const SILENT_LOGIN = 'SILENT_LOGIN';
export const LOGIN_METAMASK = 'LOGIN_METAMASK';
export const SET_PROVIDER = 'SET_PROVIDER';
export const LOG_OUT = 'LOG_OUT';
export const SET_ACC_CHANGE = 'SET_ACC_CHANGE';

/**
 * MUTATION
 */
export const MUTATE_NETWORK = 'MUTATE_NETWORK';
export const MUTATE_ADDRESS = 'MUTATE_ADDRESS';
export const MUTATE_USERNAME = 'MUTATE_USERNAME';
export const MUTATE_AVATAR = 'MUTATE_AVATAR';
export const MUTATE_USERNAME_EXISTENCE = 'MUTATE_USERNAME_EXISTENCE';
export const MUTATE_EDIT_PROFILE_RESULT = 'MUTATE_EDIT_PROFILE_RESULT';
export const MUTATE_CREATED_ASSETS_PACKS_IDS = 'MUTATE_CREATED_ASSETS_PACKS_IDS';
export const MUTATE_BOUGHT_ASSETS_PACKS_IDS = 'MUTATE_BOUGHT_ASSETS_PACKS_IDS';
export const MUTATE_BALANCES = 'MUTATE_BALANCES';
export const MUTATE_NOTIFICATIONS = 'MUTATE_NOTIFICATIONS';
export const MUTATE_APPROVAL = 'MUTATE_APPROVAL';
export const MUTATE_CONNECT_PROVIDER = 'MUTATE_CONNECT_PROVIDER';
export const MUTATE_CONNECT_PROVIDER_SUCCESS = 'MUTATE_CONNECT_PROVIDER_SUCCESS';
export const MUTATE_LOGGING_IN = 'MUTATE_LOGGING_IN';
