/**
 * GETTERS
 */
export const METAMASK_ADDRESS = 'METAMASK_ADDRESS';
export const USERNAME = 'USERNAME';
export const AVATAR = 'AVATAR';
export const USERNAME_EXISTENCE = 'USERNAME_EXISTENCE';
export const EDIT_PROFILE_RESULT = 'EDIT_PROFILE_RESULT';
export const CREATED_ASSETS_ID = 'CREATED_ASSETS_ID';

/**
 * ACTIONS
 */
export const SET_METAMASK_ADDRESS = 'SET_METAMASK_ADDRESS';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_AVATAR = 'SET_AVATAR';
export const SET_USER_CONFIG = 'SET_USER_CONFIG';
export const UPDATE_USER_CONFIG = 'UPDATE_USER_CONFIG';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const CHECK_USERNAME_EXISTENCE = 'CHECK_USERNAME_EXISTENCE';
export const SET_CREATED_ASSETS = 'SET_CREATED_ASSETS';

// /**
//  * MUTATION
//  */
export const MUTATE_METAMASK_ADDRESS = 'MUTATE_METAMASK_ADDRESS';
export const MUTATE_USERNAME = 'MUTATE_USERNAME';
export const MUTATE_AVATAR = 'MUTATE_AVATAR';
export const MUTATE_USERNAME_EXISTENCE = 'MUTATE_USERNAME_EXISTENCE';
export const MUTATE_EDIT_PROFILE_RESULT = 'MUTATE_EDIT_PROFILE_RESULT';
export const MUTATE_CREATED_ASSETS_ID = 'MUTATE_CREATED_ASSETS_ID';