/**
 * GETTERS
 */
export const CANVAS_DRAWING = 'CANVAS_DRAWING';
export const SELECTED_ASSET_PACKS = 'SELECTED_ASSET_PACKS';

/**
 * ACTIONS
 */
export const START_CANVAS_DRAWING = 'START_CANVAS_DRAWING';
export const FINISH_CANVAS_DRAWING = 'FINISH_CANVAS_DRAWING';
export const TOGGLE_ASSET_PACK = 'TOGGLE_ASSET_PACK';
export const SELECT_SINGLE_ASSET_PACK = 'SELECT_SINGLE_ASSET_PACK';
export const CLEAR_ASSET_PACKS = 'CLEAR_ASSET_PACKS';
export const SET_SELECTED_ASSET_PACKS = 'SET_SELECTED_ASSET_PACKS';

/**
 * MUTATION
 */
export const MUTATE_CANVAS_DRAWING = 'MUTATE_TOGGLE_CANVAS_DRAWING';
export const MUTATE_SELECTED_ASSET_PACKS = 'MUTATE_SELECTED_ASSET_PACKS';