/**
 * GETTERS
 */
export const CANVAS_DRAWING = 'CANVAS_DRAWING';
export const SELECTED_ASSET_PACKS = 'SELECTED_ASSET_PACKS';

/**
 * ACTIONS
 */
export const TOGGLE_CANVAS_DRAWING = 'TOGGLE_CANVAS_DRAWING';
export const TOGGLE_ASSET_PACK = 'TOGGLE_ASSET_PACK';
export const SELECT_SINGLE_ASSET_PACK = 'SELECT_SINGLE_ASSET_PACK';

/**
 * MUTATION
 */
export const MUTATE_CANVAS_DRAWING = 'MUTATE_TOGGLE_CANVAS_DRAWING';
export const MUTATE_SELECTED_ASSET_PACKS = 'MUTATE_SELECTED_ASSET_PACKS';