/**
 * GETTERS
 */
export const MODAL = 'MODAL';
export const CONTENT = 'CONTENT';
export const LOADING_MODAL = 'LOADING_MODAL';
export const LOADING_CONTENT = 'LOADING_CONTENT';


/**
 * ACTIONS
 */
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const TOGGLE_LOADING_MODAL = 'TOGGLE_LOADING_MODAL';
export const HIDE_LOADING_MODAL = 'HIDE_LOADING_MODAL';
export const CHANGE_LOADING_CONTENT = 'CHANGE_LOADING_CONTENT';

// /**
//  * MUTATION
//  */
export const MUTATE_MODAL = 'MUTATE_MODAL';
export const MUTATE_CONTENT = 'MUTATE_CONTENT';

export const MUTATE_LOADING_MODAL = 'MUTATE_LOADING_MODAL';
export const MUTATE_LOADING_CONTENT = 'MUTATE_LOADING_CONTENT';
