/**
 * GETTERS
 */
export const METAMASK_ADDRESS = 'METAMASK_ADDRESS';
export const USERNAME = 'USERNAME';
export const USERNAME_EXISTENCE = 'USERNAME_EXISTENCE';
export const CHANGE_USERNAME_RESULT = 'CHANGE_USERNAME_RESULT';

/**
 * ACTIONS
 */
export const SET_USER_CONFIG = 'SET_USER_CONFIG';
export const UPDATE_USER_CONFIG = 'UPDATE_USER_CONFIG';
export const SET_METAMASK_ADDRESS = 'SET_METAMASK_ADDRESS';
export const SET_USERNAME = 'SET_USERNAME';
export const CHANGE_USERNAME = 'CHANGE_USERNAME';
export const CHECK_USERNAME_EXISTENCE = 'CHECK_USERNAME_EXISTENCE';

// /**
//  * MUTATION
//  */
export const MUTATE_METAMASK_ADDRESS = 'MUTATE_METAMASK_ADDRESS';
export const MUTATE_USERNAME = 'MUTATE_USERNAME';
export const MUTATE_USERNAME_EXISTENCE = 'MUTATE_USERNAME_EXISTENCE';
export const MUTATE_USERNAME_RESULT = 'MUTATE_USERNAME_RESULT';