/**
 * GETTERS
 */
export const METAMASK_ADDRESS = 'METAMASK_ADDRESS';
export const USERNAME = 'USERNAME';

/**
 * ACTIONS
 */
export const SET_USER_CONFIG = 'SET_USER_CONFIG';
export const UPDATE_USER_CONFIG = 'UPDATE_USER_CONFIG';
export const SET_METAMASK_ADDRESS = 'SET_METAMASK_ADDRESS';
export const SET_USERNAME = 'SET_USERNAME';
export const EDIT_USERNAME = 'EDIT_USERNAME';

// /**
//  * MUTATION
//  */
export const MUTATE_METAMASK_ADDRESS = 'MUTATE_METAMASK_ADDRESS';
export const MUTATE_USERNAME = 'MUTATE_USERNAME';